//------------------------------------------------------------------------
// Copyright(c) 2022 Hussein Taher.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake
#include "projectversion.h"

#define stringOriginalFilename "Takoyaki.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription "Takoyaki VST3 (64Bit)"
#else
#define stringFileDescription "Takoyaki VST3"
#endif
#define stringCompanyName "Hussein Taher\0"
#define stringLegalCopyright "Copyright(c) 2022 Hussein Taher."
#define stringLegalTrademarks \
    "VST is a trademark of Steinberg Media Technologies GmbH"
