get_filename_component(srcdir "${CMAKE_SOURCE_DIR}" REALPATH)
get_filename_component(bindir "${CMAKE_BINARY_DIR}" REALPATH)

if("${srcdir}" STREQUAL "${bindir}")
    message("=========================================================")
    message("Warning: in-source builds are disabled!")
    message("Please create a separate build folder using the -B flag")
    message("=========================================================")
    message(FATAL_ERROR "Quitting configuration!")
endif()