name: clang-format

on: [push]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: clang-format lint
      uses: DoozyX/clang-format-lint-action@v0.12
      with:
        clangFormatVersion: 12
        inplace: true

    - name: Add & Commit
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        pull: "--rebase --autostash"
        message: "Formatted files using clang-format"